language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_script:
    - cp Tests/Fixtures/App/app/config/parameters.yml.dist Tests/Fixtures/App/app/config/parameters.yml
    - composer install --dev
    - ./Tests/Fixtures/App/app/console propel:database:create
    - ./Tests/Fixtures/App/app/console propel:sql:insert
    - ./Tests/Fixtures/App/app/console propel:build

notifications:
  email:
    - maxime.corson@spyrit.net
    - charles.henzel@spyrit.net
    - pierre-yves.guerder@spyrit.net