language: php

php:
    - 5.6

services:
  - mysql

before_script:
    - cp Tests/Fixtures/App/app/config/parameters.yml.dist Tests/Fixtures/App/app/config/parameters.yml
    - composer install --dev
    - ./Tests/Fixtures/App/app/console propel:database:create
    - ./Tests/Fixtures/App/app/console propel:sql:insert --force
    - ./Tests/Fixtures/App/app/console propel:build -vvv

notifications:
  email:
    - pierre-yves.guerder@spyrit.net
